### ISSUE TITLE
Remove permissions_descriptor and total_supply

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#85]
# Clarification and motivation

Total supply is no longer required by FA2 and the corresponding entrypoint has been removed from our contract. However, we still store it in the storage. It's really not expensive to store, but there was a request to remove it completely to make the contract a bit smaller.

Also, `permissions_descriptor` is apparently not required by FA2 anymore, hence we can remove it as well.

# Acceptance criteria

1. `total_supply` is not stored anymore.
2. `permissions_descriptor` entrypoint is removed from the contract (and the specification) if it's not required by FA2 (please check that).

**Comment by sras** [comment]
@gromakovsky Regarding `permissions_descriptor` it appears that the FA2 doc says if the contract does not implement the default permission policy (also defined by FA2 spec), then the contract should expose the permissions_descriptor. And the default is [appears to be](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#interface-specification) ,

```
let default_descriptor : permissions_descriptor = {
  operator = Owner_or_operator_transfer;
  receiver = Owner_no_hook;
  sender = Owner_no_hook;
  custom = (None: custom_permission_policy option);
}
```

It seems since we are using `Optional_owner_hook` for sender and receiver hooks fields, we must leave the permissions descriptor.

**Comment by gromakovsky** [comment]
Aha, interesting, that's something new to me.

>  I suppose we should do that.

Let me ask in #tq-serokell about that just in case.

**Comment by gromakovsky** [comment]
> please disregard permission descriptor for this contract as we want to expedite it and golf as much gas as we can w/o losing functionality

@sras so we should update transfer behavior by removing optional hooks and remove permission descriptor completely (implying the default one).
