### ISSUE TITLE
Investigate and add Permit

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#87]
# Clarification and motivation

There is this repo: https://github.com/tqtezos/lorentz-contract-permit

There was a request to add Permit to stablecoin. I haven't seen that repo before and I don't know what Permit is, so we should investigate it first.

# Acceptance criteria

1. Figure out how that repo can be used and what it does, ask questions if necessary.
2. Incorporate it into this repo.

**Comment by sras** [comment]
In the [TZIP](https://gitlab.com/tzip/tzip/-/blob/e55e0b62a3b16ac2dbf6116d96155f7a024a9da4/proposals/tzip-17/tzip-17.md) it is written that. 

> Any user who knows the hashed parameters can call the target contract on behalf of the signer, consuming the Permit.

But I doubt that the permit check can only a given address against a permit, and cannot extract an address out of the permit. So if the contract have stored the address of an admin in the storage, then permit check can ensure a certain parameter has been signed by the admin. This means that it can work with administrative entrypoints, but cannot easily work with entrypoints like 'mint'. Because in that entrypoint, we right now fetch the minter address using `SENDER` and the parameter

```
type mint_param_ is record
  to_    : address
; amount : nat
end
```

does not contain the minter address. So in this case, we cannot use the permit to allow any users to call the contract on behalf of a minter. We can walk through all the minters in the contract and check each of them until one succeeds, but I am not sure if that is practical. Operator transfer also a appear problematic in similar way.

How shall we proceed with implementing permit for such entrypoints?
